### PR TITLE
Latest shared libraries from Dewesoft

### PR DESCRIPTION
**Pull request by costerwi**

### CODE REVIEW

**Comment by fleimgruber** [comment]
First off, I don't _really_ know what is going on here, but some observations
nonetheless.

My gut feeling is that this is a bug in the DWDataReader shared library code.
Where `DWGetChannelProps` returns the wrong number for channel index length.

On Linux CI, this leads to reading 2 excess bytes (whose values seem random,
i.e. whatever is there in memory) which can be interpreted as ASCII characters
in some cases (https://travis-ci.org/costerwi/dwdatareader/jobs/319152454) and
cannot be interpreted in other cases
(https://travis-ci.org/costerwi/dwdatareader/jobs/319152452).

On Windows CI, this only happens for Python >= 3.5 and there only one excess
byte is read.

On my Windows dev machine with Python 3.6 all tests pass, though.

So now I am curious: What do you see on your Linux dev machine? Also passing?

**Comment by costerwi** [comment]
Sorry, I haven't been able to spend time debugging this lately. It also fails on my linux machine.

Like you, my first thought was that there is a problem in the DLL. It returns the wrong length. I can't figure out why different Python versions consistently receive different lengths from the DLL. It seems like it should be Python independent.

**Comment by fleimgruber** [comment]
I can reproduce the issue on a Linux VM.  I will try to look into this.

**Comment by costerwi** [comment]
Obsolete

**Pull request closed without merging**
