### PR TITLE
Bug Fixing and update with newest library

### PR DESCRIPTION
**Pull request by matrixx567**
Hello Carl,

thank you for your nice Python interface for the DewSoft data files.
After trying your code i get the following Exeption

```
__init__.py in scaled(self)
    110         import numpy
    111         count = DLL.DWGetScaledSamplesCount(self.index)
--> 112         data = numpy.empty(count, dtype=numpy.double)
    113         time = numpy.empty_like(data)
    114         stat = DLL.DWGetScaledSamples(self.index, 0, count,

ValueError: negative dimensions are not allowed
```

The error arrised from a missing ```call_by``` parameter and I fixed this bug immediatelly.
I also moved the logic code into an own module and updated the DeweSoft library to the newest available version from the DeweSoft homepage.

Thanks for the nice module,
Martin

### CODE REVIEW

**Comment by costerwi** [comment]
Thanks Martin! I haven't experienced that error in my files.

There are a lot of changes here. Could you be more specific about what you did to fix the error?

**Comment by matrixx567** [comment]
All correction to the logical functions are in the commit 9c7d4ccce2e0731db1bda700cdcd15b106121998. 

The exception above was generated by the ```DLL.DWGetChannelList(self.channels)``` call. With the example files from DeweSoft I figured out that a byref function was missed (```DLL.DWGetChannelList(ctypes.byref(self.channels))```).

Then I updated all parameters of the library functions to the given ones in the DeweSoft example.

After that I moved the code away from the ```__init__.py``` into an own module, updated the version number and the example code in the readme.

**Comment by matrixx567** [comment]
Hello,

After some tests I figured out that the exception comes from the ```DLL.DWAddReader()``` call. If I call this method before ```DLL.DWGetNumReaders(ctypes.pointer(num_readers))``` the library works fine.

This is an example I called the DWFile

```python
class DWFile(collections.Mapping):
    """Data file type mapping channel names their metadata"""

    def __init__(self, source=None):
        self.name = ''       # Name of the open file
        self.closed = True   # bool indicating the current state of the reader
        self.delete = False  # Whether to remove file when closed

        stat = DLL.DWAddReader()  # Add reader to be used by next DWFile instance
        if stat:
            self.close()
            raise DWError(stat)
            
        num_readers = ctypes.c_int()
        stat = DLL.DWGetNumReaders(ctypes.pointer(num_readers))
        if stat:
            raise DWError(stat)
        self.readerID = num_readers.value - 1
        
        if source:
            self.open(source)  # If this fails then the instance is not constructed
```

**Comment by costerwi** [comment]
Thanks. If you pull the latest version it should work better. It includes many improvements, including better error reporting.

**Comment by matrixx567** [comment]
Hallo,
I tested it with some example data and it works fine. It shows the data without any error.
Thank you

**Pull request closed without merging**
